fix builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,27 +48,31 @@ jobs:
       - name: Install dependencies
         run: cabal update
 
-      - name: Build executable
+      - name: Build executable on Linux or macOS
+        if: runner.os != 'Windows'
         run: |
           cabal build
           mkdir -p dist
-          if [ "${{ runner.os }}" == "Windows" ]; then
-            $BIN_PATH = cabal list-bin json-to-sql-exe
-            if (Test-Path $BIN_PATH) {
-              Copy-Item $BIN_PATH dist/json-to-sql-windows.exe
-            } else {
-              Write-Error "Error: Executable not found!"
-              exit 1
-            }
+          BIN_PATH=$(cabal list-bin json-to-sql-exe)
+          if [[ -f "$BIN_PATH" ]]; then
+            cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
           else
-            BIN_PATH=$(cabal list-bin json-to-sql-exe)
-            if [[ -f "$BIN_PATH" ]]; then
-              cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
-            else
-              echo "Error: Executable not found!"
-              exit 1
-            fi
+            echo "Error: Executable not found!"
+            exit 1
           fi
+
+      - name: Build executable on Windows
+        if: runner.os == 'Windows'
+        run: |
+          cabal build
+          mkdir -p dist
+          BIN_PATH=$(cabal list-bin json-to-sql-exe)
+          if (Test-Path $BIN_PATH) {
+            Copy-Item $BIN_PATH dist/json-to-sql-windows.exe
+          } else {
+            Write-Error "Error: Executable not found!"
+            exit 1
+          }
 
       - name: Upload built executables
         uses: actions/upload-artifact@v4
