add windows fallback

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,12 +52,22 @@ jobs:
         run: |
           cabal build
           mkdir -p dist
-          BIN_PATH=$(cabal list-bin json-to-sql-exe)
-          if [[ -f "$BIN_PATH" ]]; then
-            cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
+          if [ "${{ runner.os }}" == "Windows" ]; then
+            $BIN_PATH = cabal list-bin json-to-sql-exe
+            if (Test-Path $BIN_PATH) {
+              Copy-Item $BIN_PATH dist/json-to-sql-windows.exe
+            } else {
+              Write-Error "Error: Executable not found!"
+              exit 1
+            }
           else
-            echo "Error: Executable not found!"
-            exit 1
+            BIN_PATH=$(cabal list-bin json-to-sql-exe)
+            if [[ -f "$BIN_PATH" ]]; then
+              cp "$BIN_PATH" dist/json-to-sql-${{ runner.os == 'Linux' && 'linux' || 'macos' }}
+            else
+              echo "Error: Executable not found!"
+              exit 1
+            fi
           fi
 
       - name: Upload built executables
